- backend/src/common/filters/socket/socket.filter.ts
바로 머지 진핸합니다. 
자세한 사용 설명은 https://github.com/3DPong/transcendence/issues/101 참고 바랍니다
> ADD: socket filter common 폴더로 이동

- frontend/config/backend.ts
- frontend/src/components/Molecule/Chat/AvatarPopper.tsx
- frontend/src/components/Molecule/Chat/Menu/MenuFooter.tsx
- frontend/src/components/Molecule/Chat/Menu/MenuList.tsx
- frontend/src/components/Molecule/Chat/Menu/UserCard.tsx
- frontend/src/components/Organism/Chat/ChannelSetting.tsx
- frontend/src/components/Organism/Chat/ChatDetail.tsx
- frontend/src/components/Organism/Chat/LocalChatList.tsx
- frontend/src/components/Organism/Chat/MenuDrawer.tsx
- frontend/src/context/ChatContext.ts
- frontend/src/context/SocketContext.tsx
- frontend/src/types/chat.ts
1. 백엔드 통합을 위해 api 경로를 추가했습니다.
config/backend.ts
```ts
export const API_URL = `http://localhost:${API_PORT}/api`;
```
2. 챗 소켓 네임스페이스 지정했습니다.
context/SocketContext.tsx
```ts
const chatConnect = ({ userId }: ChatConnectProps) => {
if (!chatSocket) {
const newSocket = io(SOCKET_URL + '/chat', {
query: {
user_id: userId,
},
});
setChatSocket(newSocket);
}
};
```
통합환경에는 로그인 관련 기능을 사용하기 힘들어서
백엔드 환경은 규림님 백엔드에 쿼리스트링 id를 추가해서 만들었습니다.
(브랜치명 : front/feat_chatsocket_back)
#133 #135
소켓 작업 최상단으로 변경해야하는 작업들은 로그인 기능이 추가되면 추가하겠습니다
> [front] 채팅 소켓 연결작업 완료 

- backend/src/common/guards/ft/ft.strategy.ts
- backend/src/common/guards/jwt/jwt.strategy.ts
- backend/src/common/guards/tokenUser/tokenUser.guard.ts
- backend/src/common/guards/tokenUser/tokenUser.strategy.ts
- backend/src/common/guards/twoFactor/twoFactor.strategy.ts
- backend/src/common/guards/userCreation/userCreation.strategy.ts
- backend/src/models/image/image.controller.ts
- backend/src/models/image/image.module.ts
- backend/src/models/user/api/dtos/createUserReq.dto.ts
- backend/src/models/user/api/dtos/updateUserReq.dto.ts
- backend/src/models/user/api/user.controller.ts
> [back] fix : 프론트 통합과정에서 로그인 관련 문제 해결

- backend/src/models/notifySocket/socket/notifySocket.module.ts
- backend/src/models/notifySocket/socket/services/notifySocket.service.ts
- 커넥션 상황에서 JWT 토큰을 검증합니다.
@kyu-baek chat 소켓에서도 처리 부탁드립니당...
> [back] FEAT: NotifySocket에서 connection 검증

- backend/src/models/chat/socket/chatSocket.gateway.ts
- backend/src/models/chat/socket/chatSocket.module.ts
- backend/src/models/chat/socket/services/chatSocket.service.ts
###
chat socket connect 상황에서도 jwt 인증 로직  추가
> [back] chat gateway jwt 추가

- backend/src/models/notifySocket/socket/services/notifySocket.service.ts
> [back] FIX: notify socket 연결 과정에 불필요한 코드로 인한 에러

- frontend/src/App.tsx
- frontend/src/api/user/userRelation.ts
- frontend/src/components/Organism/Controller/Controller.tsx
- frontend/src/components/Organism/Friends/GlobalUserList/ActionMenu.tsx
- frontend/src/components/Organism/Friends/GlobalUserList/GlobalUserList.tsx
- frontend/src/components/Organism/Friends/LocalUserList/ActionMenu.tsx
- frontend/src/components/Organism/Friends/LocalUserList/List.tsx
- frontend/src/components/Organism/Friends/LocalUserList/LocalUserList.tsx
- frontend/src/components/Organism/Friends/LocalUserList/UserListRow.tsx
- frontend/src/components/Organism/Game/Game.tsx
- frontend/src/components/Organism/Game/Renderer/Renderer.tsx
- frontend/src/components/Organism/Login/SignUp.tsx
- frontend/src/types/notify.ts
- frontend/src/types/user.ts
> [front] Notify 소켓 연결 완료!

- backend/src/models/user/api/dtos/getUserHistoryRes.dto.ts
- backend/src/models/user/api/services/user.service.ts
- backend/src/models/user/api/user.controller.ts
- backend/src/models/user/api/user.module.ts
- user profile 에서 사용할 예정이기 때문에 10개만 받습니다.
- API 명세 참조해주세요.
> [back] FEAT: get user game history

- backend/src/models/game/gameData/InGameData.ts
- backend/src/models/game/simul/object/ObjectController.ts
- backend/src/models/game/socket/services/game.data.maker.ts
> [back] 공 초기속도 보정 및 각도 제한

- backend/src/models/user/api/dtos/searchUserRes.dto.ts
- `||` 으로 인해서 boolean 결과가 반영되었습니다.
- `||`로 잘못 코딩된 부분을 수정했습니다.
> [back] fix: #165 해결

- frontend/src/App.tsx
- frontend/src/components/ChatProfileTemplate.tsx
- frontend/src/components/ChatTemplate.tsx
- frontend/src/components/Molecule/Chat/AvatarPopper.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageCard.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageHeader.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageList.tsx
- frontend/src/components/Molecule/Chat/SearchList.tsx
- frontend/src/components/Organism/Chat/ChannelSetting.tsx
- frontend/src/components/Organism/Chat/ChatDetail.tsx
- frontend/src/components/Organism/Chat/CreateChat.tsx
- frontend/src/components/Organism/Chat/GlobalChatList.tsx
- frontend/src/components/Organism/Chat/LocalChatList.tsx
- frontend/src/components/Organism/Chat/MenuDrawer.tsx
- frontend/src/context/SocketContext.tsx
- frontend/src/types/chat.ts
* 테스트를 위해 쿼리스트링으로 user_id 전달하는 코드 제거 
* 채팅방 초대할때 유저리스트 api를 /user/search로 변경
* 채팅방에서 DM, ViewProfile 간단한 연결구현 (DM은 추가로 연결해야할부분이 있고, profile은 css 변경필요)
* 채팅방에서 게임초대 방식 수정
> [front] 채팅방 관련 기능 수정

- backend/src/models/game/enum/GameEnum.ts
- backend/src/models/game/gameData/InviteData.ts
- backend/src/models/game/gameData/MatchJoinData.ts
- backend/src/models/game/simul/GameManager.ts
- backend/src/models/game/socket/game.gateway.ts
- backend/src/models/game/socket/services/game.service.ts
> [back] in chat room (game join, game watch)

- backend/src/models/chat/api/chat.controller.ts
- backend/src/models/chat/api/services/chat.service.ts
- backend/src/models/chat/entities/dmChannel.entity.ts
- backend/src/models/chat/socket/chat.interface.ts
- backend/src/models/chat/socket/chatSocket.gateway.ts
- backend/src/models/chat/socket/chatSocket.module.ts
- backend/src/models/chat/socket/services/chatSocket.service.ts
> [Back] chat DM 프론트 요청사항 반영

- backend/src/models/chat/api/services/chat.service.ts
- backend/src/models/chat/dto/channel.dto.ts
- backend/src/models/chat/dto/socket.dto.ts
- backend/src/models/chat/entities/messageLog.entity.ts
- backend/src/models/chat/socket/chat.interface.ts
- backend/src/models/chat/socket/services/chatSocket.service.ts
```
export enum MessageType {
MESSAGE = 'message',
GAME = 'game',
}
```
> [Back] chat 엔티티 추가 + dm 중복 생성 수정

- frontend/src/App.tsx
- frontend/src/api/API.ts
- frontend/src/api/chat/chat.ts
- frontend/src/components/Molecule/Chat/AvatarPopper.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageCard.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageHeader.tsx
- frontend/src/components/Organism/Chat/ChannelSetting.tsx
- frontend/src/components/Organism/Chat/ChatDetail.tsx
- frontend/src/components/Organism/Chat/CreateChat.tsx
- frontend/src/components/Organism/Chat/LocalChatList.tsx
- frontend/src/components/Organism/Chat/MenuDrawer.tsx
- frontend/src/components/Organism/Friends/GlobalUserList/ActionMenu.tsx
- frontend/src/components/Organism/Friends/LocalUserList/ActionMenu.tsx
- frontend/src/components/Organism/Game/ChooseMode.tsx
- frontend/src/components/Organism/Game/Game.tsx
- frontend/src/components/Organism/Game/GameStartButton.tsx
- frontend/src/components/Organism/Home/Controller/Controller.tsx
- frontend/src/context/MatchDataContext.tsx
- frontend/src/types/chat.ts
- frontend/src/types/game.ts
게임 초대메시지, 채팅방내부, 유저리스트 DM 기능 연결했습니다  #159
큰 구현은 대부분 끝났고 앞으로는 자잘하게 버그 수정 정도만 하면 될거같네요 
* 초대받은 플레이어는 chatJoin 이벤트에 gameId만 전달
* 초대받은 플레이어는 chatJoin 이벤트의 응답으로 메시지를 emit 하지 않아야함
* inviteData 타입에 게임모드 추가
* 관전자 기능 백엔드 완성되면 좀더 수정 필요 
* 채팅방 썸네일도 동작 이상한 부분이 있어서 수정이 예상되네요
> [front] 게임 초대메시지, DM 기능 연결

- backend/src/models/game/gameData/InviteData.ts
- backend/src/models/game/socket/game.gateway.ts
- backend/src/models/game/socket/services/game.service.ts
> [back] in chat room (game join, game watch) 오류 fix

- frontend/.gitignore
- frontend/config/backend.ts
- frontend/config/webpack.common.js
- frontend/env.sample
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/api/API.ts
- frontend/src/api/user/userData.ts
- frontend/src/api/user/userHistory.ts
- frontend/src/api/user/userRelation.ts
- frontend/src/components/Molecule/AlertSnackbar.tsx
- frontend/src/components/Organism/Friends/LocalUserList/List.tsx
- frontend/src/components/Organism/Game/Game.tsx
- frontend/src/components/Organism/Game/GameStartButton.tsx
- frontend/src/components/Organism/Game/Renderer/Renderer.tsx
- frontend/src/components/Organism/Home/Controller/Controller.tsx
- frontend/src/components/Organism/Login/LoginError.tsx
- frontend/src/components/Organism/Login/ServerError.tsx
- frontend/src/components/Organism/Login/SignIn.tsx
- frontend/src/components/Organism/Login/SignInDuplicatedError.tsx
- frontend/src/components/Organism/Login/SignInError.tsx
- frontend/src/components/Organism/Profile/ProfileStatistic.tsx
- frontend/src/context/SocketContext.tsx
- frontend/tsconfig.json
변경사항
1. 소켓 연결부를 모두 Controller로 이동
2. 중복 로그인 에러 처리 
3. 메뉴 버튼 클릭 무반응 에러 처리
4. frontend/.env 파일로 환경변수 받아오도록 수정
상세한 내용은 하단 Comment에 남긴 주석 참조 부탁드립니다.
> [front] 중복 로그인, Controller 버튼 무반응 등 전반적 에러 수정

- backend/src/models/chat/socket/chatSocket.gateway.ts
- backend/src/models/notifySocket/socket/services/notifySocket.service.ts
#180  수정중에 첫 로그인에서 발생하는 문제 해결했습니다.
> [back] fix: 소켓 아이디가 할당 안된 경우 온라인으로 뜨는 문제 해결

- frontend/package.json
- frontend/src/components/Organism/Game/GameStartButton.tsx
- frontend/src/components/Organism/Home/Renderer/Renderer.tsx
- frontend/src/context/SocketContext.tsx
- frontend/tsconfig.json
> [front] 게임모드 선택창 에러 수정

- backend/src/providers/redis/socketMap.service.ts
refactor: key 값 형식을 뱉는 함수 생성
#185 에서 리팩터링하면서 키값을 하나 안바꿔서 redis에서 값이 삭제되지 않았습니다. 이를 해결했습니다.
또한, 이런 문제를 방지하기 위해서 함수화하였습니다.
> [back] fix: key 이름 설정 잘못해서 발생한 문제 해결

- backend/src/models/chat/socket/chatSocket.gateway.ts
`{user_id} -> user_id`
정상작동 확인해서 바로 머지합니다.
> [back] fix: 채팅 소켓 disconnect 시 정리 안되는 문제 해결

- backend/src/models/chat/socket/chatSocket.gateway.ts
- backend/src/providers/redis/socketMap.service.ts
> [all] sync back/develop

- frontend/src/components/Molecule/Chat/List/ChannelCard.tsx
- frontend/src/components/Molecule/Chat/List/ChannelList.tsx
- frontend/src/components/Organism/Chat/ChannelSetting.tsx
- frontend/src/components/Organism/Chat/CreateChat.tsx
- frontend/src/components/Organism/Chat/LocalChatList.tsx
- frontend/src/types/chat.ts
기본썸네일을 없애고 썸네일 없는경우 null로 처리했습니다.
> [front] 기본썸네일 채팅방 버그 수정 

- backend/src/app.service.ts
- redis 에서 소켓 저장된 내용들이 문제가 생기던거라서 서버 새로 시작할 때 redis store 비워버렸습니다.
> [back] fix: 서버가 내려갔다가 올라올 때 redis가 초기화되지 않아서 발생한 문제를 임시 해결함.

- backend/src/common/filters/http/httpException.filter.ts
- backend/src/models/chat/api/chat.controller.ts
- backend/src/models/chat/api/services/chat.service.ts
- backend/src/models/chat/dto/channel.dto.ts
- backend/src/models/chat/dto/socket.dto.ts
- backend/src/models/chat/socket/chat.interface.ts
- backend/src/models/chat/socket/chatSocket.gateway.ts
- backend/src/models/chat/socket/services/chatSocket.service.ts
1. Http exception filter 수정
2. Gateway dto 삭제
> [Back]chat dto

- backend/src/models/game/gameData/OnSceneObserverData.ts
- backend/src/models/game/socket/services/game.data.maker.ts
- backend/src/models/game/socket/services/game.service.ts
> [back] 관전자 데이터 변경

- frontend/src/components/ChatTemplate.tsx
- frontend/src/components/Molecule/Chat/Detail/MessageHeader.tsx
- frontend/src/components/Organism/Chat/GlobalChatList.tsx
- frontend/src/components/Organism/Chat/LocalChatList.tsx
- frontend/src/components/Organism/Friends/GlobalUserList/GlobalUserList.tsx
- frontend/src/components/Organism/Friends/LocalUserList/LocalUserList.tsx
> [front] 배경색 채워넣기

- frontend/src/components/Molecule/AlertSnackbar.tsx
- frontend/src/components/Organism/Game/Game.tsx
- frontend/src/components/Organism/Game/GameStartButton.tsx
- frontend/src/components/Organism/Game/Renderer/Renderer.tsx
- frontend/src/types/game.ts
> [front] 게임 옵저버 수정 완료

- frontend/src/components/Organism/Chat/CreateChat.tsx
> [front] 채팅방 생성 배경

- backend/src/models/chat/socket/chatSocket.gateway.ts
- duplicate 상황에서도 채팅 소켓 내용을 disconnect 에서 날려버려서 소켓 문제가 발생했습니다. 이를 해결했습니다.
> [back] fix: chat duplicate disconnect 시 소켓 정보를 지워버리는 문제 해결

- backend/src/models/user/api/services/user.service.ts
- search 할 때 유저간의 관계를 필터링하는 것을 놓친 부분을 해결했습니다.
> [back] fix: search status 잘못 받아오는거 변경

- frontend/src/components/Organism/Chat/ChannelSetting.tsx
> [front] setting chat 에서 비밀번호 null 보낼 수 있게 변경

- frontend/src/components/Organism/Game/Renderer/Renderer.tsx
- frontend/src/components/Organism/Login/SignIn.tsx
> [front] fix: 기타 수정 완료

- frontend/src/components/Organism/Friends/GlobalUserList/UserListRow.tsx
- frontend/src/components/Organism/Profile/Profile.tsx
> [front] fix: 상태 표기 및 프로필 표기 수정 완료

- backend/src/models/user/api/dtos/searchUserRes.dto.ts
- backend/src/models/user/api/services/user.service.ts
relation에서 관계를 잘못들고오고 있었습니다. 이를 수정함.
> [back] fix: search user 의 상태를 받아오지 못하는 문제
